openapi: "3.0.3"
info:
  title: An API based on the Swimply graphql API
  version: 1.0.0
  contact:
    name: We Futurize
    email: kris.bulte@we-futurize.be
servers:
  - url: https://www.swimply.com/api
paths:
  /amenities:
    summary: An amenity is something considered to benefit a location e.g. a grill, WIFI or a kiddie pool
    get:
      tags:
        - "ammenity"
      operationId: getAmenities
      description: "Returns all amenities known in the platform"
      responses:
        '200':
          description: "A list of amenities"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Amenity'
  /users:
    summary: A user is a person registered on the platform and can function as guest who can book or as host pools.
    get:
      tags:
        - "user"
      operationId: getUsers
      description: "Returns all users known in the platform"
      responses:
        '200':
          description: "A list of users"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - "user"
      operationId: addUser
      description: "User object that needs to be added to the platform"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: "A user resource has been created"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
        '422':
          description: "A user resource could not be created because a field was missing or had an incorrect value"
          content: {}
    put:
      tags:
        - "user"
      operationId: updateUser
      description: "User object that needs to be updated"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '204':
          description: "The user resource has been updated"
          content: {}
  /pools:
      summary: A list of pools available for renting.
      get:
        tags:
          - "pool"
        operationId: getPools
        description: "Returns all pools"
        responses:
          '200':
            description: "A list of pools"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Pool'
      post:
        tags:
          - "pool"
        operationId: addPools
        description: "Pool object that needs to be added to the platform"
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pool'
        responses:
          '201':
            description: "A pool resource has been created"
            content:
              application/json:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/Pool'
          '422':
            description: "A pool resource could not be created because a field was missing or had an incorrect value"
            content: {}
      put:
        tags:
          - "pool"
        operationId: updatePools
        description: "Pool object that needs to be updated"
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pool'
        responses:
          '204':
            description: "The pool resource has been updated"
            content: {}
  /my-pools:
    summary: A list of pools you own as a host
    get:
      tags:
        - "pool"
      operationId: getMyPools
      description: "Returns all pools you own"
      responses:
        '200':
          description: "A list of pools owned by you"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pool'
     
components:
  schemas:
    Amenity:
      type: object
      required:
      - id
      - name
      - active
      - premium
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        icon: 
          type: string
        active:
          type: boolean
        image:
          type: string
        categorgy:
          type: string
        premium:
          type: boolean
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - e-mail
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        image-url:
          type: string
        e-mail:
          type: string
        phonenumber:
          type: string
        country:
          type: string
        e-mail-verified:
          type: boolean
        last-pool-id:
          type: integer
          format: int32
        pools-count:
          type: integer
          format: int32
    Pool:
      type: object
      required:
      - id
      - full-address
      - hourly-price
      - pool-width
      - pool-length
      properties:
        id:
          type: integer
          format: int64
        full-address:
          type: string
        hourly-price: 
          type: number
          format: float
        pool-width:
          type: number
          format: float
        pool-length:
          type: number
          format: float
        pool-type:
          type: string
        max-guests:
          type: integer
          format: int32
        rating:
          type: number
          format: float
        
tags:
  - name: ammenity
    description: Benefits of a location
  - name: user
    description: Registered account on the platform to book or host pools
  - name: pool
    description: Hourly private pools listed on the platform
  
